-define(EMQ_PROTOCOL_REQ, 16#70).
-define(EMQ_PROTOCOL_RES, 16#80).
-define(EMQ_PROTOCOL_EVENT, 16#90).

-define(EMQ_PROTOCOL_CMD_AUTH, 16#A).
-define(EMQ_PROTOCOL_CMD_PING, 16#B).
-define(EMQ_PROTOCOL_CMD_STAT, 16#C).
-define(EMQ_PROTOCOL_CMD_SAVE, 16#D).
-define(EMQ_PROTOCOL_CMD_FLUSH, 16#E).
-define(EMQ_PROTOCOL_CMD_DISCONNECT, 16#F).

-define(EMQ_PROTOCOL_CMD_USER_CREATE, 16#1E).
-define(EMQ_PROTOCOL_CMD_USER_LIST, 16#1F).
-define(EMQ_PROTOCOL_CMD_USER_RENAME, 16#20).
-define(EMQ_PROTOCOL_CMD_USER_SET_PERM, 16#21).
-define(EMQ_PROTOCOL_CMD_USER_DELETE, 16#22).

-define(EMQ_PROTOCOL_CMD_QUEUE_CREATE, 16#23).
-define(EMQ_PROTOCOL_CMD_QUEUE_DECLARE, 16#24).
-define(EMQ_PROTOCOL_CMD_QUEUE_EXIST, 16#25).
-define(EMQ_PROTOCOL_CMD_QUEUE_LIST, 16#26).
-define(EMQ_PROTOCOL_CMD_QUEUE_RENAME, 16#27).
-define(EMQ_PROTOCOL_CMD_QUEUE_SIZE, 16#28).
-define(EMQ_PROTOCOL_CMD_QUEUE_PUSH, 16#29).
-define(EMQ_PROTOCOL_CMD_QUEUE_GET, 16#2A).
-define(EMQ_PROTOCOL_CMD_QUEUE_POP, 16#2B).
-define(EMQ_PROTOCOL_CMD_QUEUE_CONFIRM, 16#2C).
-define(EMQ_PROTOCOL_CMD_QUEUE_SUBSCRIBE, 16#2D).
-define(EMQ_PROTOCOL_CMD_QUEUE_UNSUBSCRIBE, 16#2E).
-define(EMQ_PROTOCOL_CMD_QUEUE_PURGE, 16#2F).
-define(EMQ_PROTOCOL_CMD_QUEUE_DELETE, 16#30).

-define(EMQ_PROTOCOL_CMD_ROUTE_CREATE, 16#31).
-define(EMQ_PROTOCOL_CMD_ROUTE_EXIST, 16#32).
-define(EMQ_PROTOCOL_CMD_ROUTE_LIST, 16#33).
-define(EMQ_PROTOCOL_CMD_ROUTE_KEYS, 16#34).
-define(EMQ_PROTOCOL_CMD_ROUTE_RENAME, 16#35).
-define(EMQ_PROTOCOL_CMD_ROUTE_BIND, 16#36).
-define(EMQ_PROTOCOL_CMD_ROUTE_UNBIND, 16#37).
-define(EMQ_PROTOCOL_CMD_ROUTE_PUSH, 16#38).
-define(EMQ_PROTOCOL_CMD_ROUTE_DELETE, 16#39).

-define(EMQ_PROTOCOL_CMD_CHANNEL_CREATE, 16#3A).
-define(EMQ_PROTOCOL_CMD_CHANNEL_EXIST, 16#3B).
-define(EMQ_PROTOCOL_CMD_CHANNEL_LIST, 16#3C).
-define(EMQ_PROTOCOL_CMD_CHANNEL_RENAME, 16#3D).
-define(EMQ_PROTOCOL_CMD_CHANNEL_PUBLISH, 16#3E).
-define(EMQ_PROTOCOL_CMD_CHANNEL_SUBSCRIBE, 16#3F).
-define(EMQ_PROTOCOL_CMD_CHANNEL_PSUBSCRIBE, 16#40).
-define(EMQ_PROTOCOL_CMD_CHANNEL_UNSUBSCRIBE, 16#41).
-define(EMQ_PROTOCOL_CMD_CHANNEL_PUNSUBSCRIBE, 16#42).
-define(EMQ_PROTOCOL_CMD_CHANNEL_DELETE, 16#43).

-define(EMQ_PROTOCOL_STATUS_SUCCESS, 16#1).
-define(EMQ_PROTOCOL_STATUS_ERROR, 16#2).
-define(EMQ_PROTOCOL_STATUS_ERROR_PACKET, 16#3).
-define(EMQ_PROTOCOL_STATUS_ERROR_COMMAND, 16#4).
-define(EMQ_PROTOCOL_STATUS_ERROR_ACCESS, 16#5).
-define(EMQ_PROTOCOL_STATUS_ERROR_MEMORY, 16#6).
-define(EMQ_PROTOCOL_STATUS_ERROR_VALUE, 16#7).
-define(EMQ_PROTOCOL_STATUS_ERROR_NOT_DECLARED, 16#8).
-define(EMQ_PROTOCOL_STATUS_ERROR_NOT_FOUND, 16#9).
-define(EMQ_PROTOCOL_STATUS_ERROR_NO_DATA, 16#A).

-define(EMQ_PROTOCOL_EVENT_NOTIFY, 16#1).
-define(EMQ_PROTOCOL_EVENT_MESSAGE, 16#2).

-define(EMQ_PROTOCOL_FLUSH_USER, 1).
-define(EMQ_PROTOCOL_FLUSH_QUEUE, 2).
-define(EMQ_PROTOCOL_FLUSH_ROUTE, 4).
-define(EMQ_PROTOCOL_FLUSH_CHANNEL, 8).

-define(EMQ_QUEUE_NONE, 0).
-define(EMQ_QUEUE_AUTODELETE, 1).
-define(EMQ_QUEUE_FORCE_PUSH, 2).
-define(EMQ_QUEUE_ROUND_ROBIN, 4).
-define(EMQ_QUEUE_DURABLE, 8).

-define(EMQ_QUEUE_SUBSCRIBE_MSG, 0).
-define(EMQ_QUEUE_SUBSCRIBE_NOTIFY, 1).

-define(EMQ_ROUTE_NONE, 0).
-define(EMQ_ROUTE_AUTODELETE, 1).
-define(EMQ_ROUTE_ROUND_ROBIN, 2).
-define(EMQ_ROUTE_DURABLE, 4).

-define(EMQ_CHANNEL_NONE, 0).
-define(EMQ_CHANNEL_AUTODELETE, 1).
-define(EMQ_CHANNEL_ROUND_ROBIN, 2).
-define(EMQ_CHANNEL_DURABLE, 4).
